import type { AppDefinition } from '@/types/app.types';

export const APP_REGISTRY: AppDefinition[] = [
  {
    id: 'terminal',
    name: 'Terminal',
    icon: '💻',
    description: 'Command line interface',
    category: 'system',
    windowConfig: {
      title: 'Terminal',
      icon: '💻',
      defaultWidth: 720,
      defaultHeight: 480,
      minWidth: 400,
      minHeight: 280,
    },
    component: 'Terminal',
    desktopShortcut: true,
    startMenuEntry: true,
    xpReward: 10,
  },
  {
    id: 'notes',
    name: 'Notes',
    icon: '📝',
    description: 'Create and manage notes',
    category: 'productivity',
    windowConfig: {
      title: 'Notes',
      icon: '📝',
      defaultWidth: 720,
      defaultHeight: 540,
      minWidth: 400,
      minHeight: 300,
    },
    component: 'Notes',
    desktopShortcut: true,
    startMenuEntry: true,
    xpReward: 10,
  },
  {
    id: 'browser',
    name: 'Browser',
    icon: '🌐',
    description: 'Web browser',
    category: 'utilities',
    windowConfig: {
      title: 'Browser',
      icon: '🌐',
      defaultWidth: 1000,
      defaultHeight: 680,
      minWidth: 480,
      minHeight: 360,
    },
    component: 'Browser',
    desktopShortcut: true,
    startMenuEntry: true,
    xpReward: 10,
  },
  {
    id: 'ai-assistant',
    name: 'AI Assistant',
    icon: '🤖',
    description: 'Your intelligent OS assistant',
    category: 'utilities',
    windowConfig: {
      title: 'AI Assistant',
      icon: '🤖',
      defaultWidth: 520,
      defaultHeight: 620,
      minWidth: 360,
      minHeight: 400,
    },
    component: 'AIAssistant',
    desktopShortcut: true,
    startMenuEntry: true,
    xpReward: 10,
  },
  {
    id: 'code-editor',
    name: 'Code Editor',
    icon: '⌨️',
    description: 'Monaco-powered code editor',
    category: 'productivity',
    windowConfig: {
      title: 'Code Editor',
      icon: '⌨️',
      defaultWidth: 960,
      defaultHeight: 640,
      minWidth: 480,
      minHeight: 360,
    },
    component: 'CodeEditor',
    desktopShortcut: true,
    startMenuEntry: true,
    xpReward: 10,
  },
  {
    id: 'file-manager',
    name: 'Files',
    icon: '📁',
    description: 'Browse your files',
    category: 'system',
    windowConfig: {
      title: 'File Manager',
      icon: '📁',
      defaultWidth: 800,
      defaultHeight: 560,
      minWidth: 400,
      minHeight: 300,
    },
    component: 'FileManager',
    desktopShortcut: true,
    startMenuEntry: true,
    xpReward: 10,
  },
  {
    id: 'flappy-bird',
    name: 'Flappy Bird',
    icon: '🐦',
    description: 'Classic Flappy Bird game',
    category: 'games',
    windowConfig: {
      title: 'Flappy Bird',
      icon: '🐦',
      defaultWidth: 480,
      defaultHeight: 640,
      minWidth: 480,
      minHeight: 640,
      isResizable: false,
    },
    component: 'FlappyBird',
    desktopShortcut: false,
    startMenuEntry: true,
    xpReward: 50,
  },
  {
    id: 'sniper-mission',
    name: 'Sniper Mission',
    icon: '🎯',
    description: 'Tactical sniper game',
    category: 'games',
    windowConfig: {
      title: 'Sniper Mission',
      icon: '🎯',
      defaultWidth: 800,
      defaultHeight: 600,
      minWidth: 640,
      minHeight: 480,
    },
    component: 'SniperMission',
    desktopShortcut: false,
    startMenuEntry: true,
    xpReward: 50,
  },
  {
    id: 'settings',
    name: 'Settings',
    icon: '⚙️',
    description: 'OS Settings',
    category: 'system',
    windowConfig: {
      title: 'Settings',
      icon: '⚙️',
      defaultWidth: 700,
      defaultHeight: 520,
      minWidth: 480,
      minHeight: 360,
    },
    component: 'Settings',
    desktopShortcut: false,
    startMenuEntry: true,
    xpReward: 5,
  },
  {
    id: 'music-player',
    name: 'Music Player',
    icon: '🎵',
    description: 'Lo-fi & chiptune music player',
    category: 'utilities',
    windowConfig: {
      title: 'Music Player',
      icon: '🎵',
      defaultWidth: 420,
      defaultHeight: 580,
      minWidth: 360,
      minHeight: 480,
      isResizable: false,
    },
    component: 'MusicPlayer',
    desktopShortcut: true,
    startMenuEntry: true,
    xpReward: 10,
  },
];

export const APPS_BY_ID = Object.fromEntries(APP_REGISTRY.map((a) => [a.id, a]));
